package com.cun.util.es.db.pojo;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class MetaTableExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meta_table
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meta_table
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meta_table
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_table
     *
     * @mbg.generated
     */
    public MetaTableExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_table
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_table
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_table
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_table
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_table
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_table
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_table
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_table
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_table
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_table
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table meta_table
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCatalogIdIsNull() {
            addCriterion("catalog_id is null");
            return (Criteria) this;
        }

        public Criteria andCatalogIdIsNotNull() {
            addCriterion("catalog_id is not null");
            return (Criteria) this;
        }

        public Criteria andCatalogIdEqualTo(Long value) {
            addCriterion("catalog_id =", value, "catalogId");
            return (Criteria) this;
        }

        public Criteria andCatalogIdNotEqualTo(Long value) {
            addCriterion("catalog_id <>", value, "catalogId");
            return (Criteria) this;
        }

        public Criteria andCatalogIdGreaterThan(Long value) {
            addCriterion("catalog_id >", value, "catalogId");
            return (Criteria) this;
        }

        public Criteria andCatalogIdGreaterThanOrEqualTo(Long value) {
            addCriterion("catalog_id >=", value, "catalogId");
            return (Criteria) this;
        }

        public Criteria andCatalogIdLessThan(Long value) {
            addCriterion("catalog_id <", value, "catalogId");
            return (Criteria) this;
        }

        public Criteria andCatalogIdLessThanOrEqualTo(Long value) {
            addCriterion("catalog_id <=", value, "catalogId");
            return (Criteria) this;
        }

        public Criteria andCatalogIdIn(List<Long> values) {
            addCriterion("catalog_id in", values, "catalogId");
            return (Criteria) this;
        }

        public Criteria andCatalogIdNotIn(List<Long> values) {
            addCriterion("catalog_id not in", values, "catalogId");
            return (Criteria) this;
        }

        public Criteria andCatalogIdBetween(Long value1, Long value2) {
            addCriterion("catalog_id between", value1, value2, "catalogId");
            return (Criteria) this;
        }

        public Criteria andCatalogIdNotBetween(Long value1, Long value2) {
            addCriterion("catalog_id not between", value1, value2, "catalogId");
            return (Criteria) this;
        }

        public Criteria andThemeIdIsNull() {
            addCriterion("theme_id is null");
            return (Criteria) this;
        }

        public Criteria andThemeIdIsNotNull() {
            addCriterion("theme_id is not null");
            return (Criteria) this;
        }

        public Criteria andThemeIdEqualTo(Long value) {
            addCriterion("theme_id =", value, "themeId");
            return (Criteria) this;
        }

        public Criteria andThemeIdNotEqualTo(Long value) {
            addCriterion("theme_id <>", value, "themeId");
            return (Criteria) this;
        }

        public Criteria andThemeIdGreaterThan(Long value) {
            addCriterion("theme_id >", value, "themeId");
            return (Criteria) this;
        }

        public Criteria andThemeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("theme_id >=", value, "themeId");
            return (Criteria) this;
        }

        public Criteria andThemeIdLessThan(Long value) {
            addCriterion("theme_id <", value, "themeId");
            return (Criteria) this;
        }

        public Criteria andThemeIdLessThanOrEqualTo(Long value) {
            addCriterion("theme_id <=", value, "themeId");
            return (Criteria) this;
        }

        public Criteria andThemeIdIn(List<Long> values) {
            addCriterion("theme_id in", values, "themeId");
            return (Criteria) this;
        }

        public Criteria andThemeIdNotIn(List<Long> values) {
            addCriterion("theme_id not in", values, "themeId");
            return (Criteria) this;
        }

        public Criteria andThemeIdBetween(Long value1, Long value2) {
            addCriterion("theme_id between", value1, value2, "themeId");
            return (Criteria) this;
        }

        public Criteria andThemeIdNotBetween(Long value1, Long value2) {
            addCriterion("theme_id not between", value1, value2, "themeId");
            return (Criteria) this;
        }

        public Criteria andTableZhNameIsNull() {
            addCriterion("table_zh_name is null");
            return (Criteria) this;
        }

        public Criteria andTableZhNameIsNotNull() {
            addCriterion("table_zh_name is not null");
            return (Criteria) this;
        }

        public Criteria andTableZhNameEqualTo(String value) {
            addCriterion("table_zh_name =", value, "tableZhName");
            return (Criteria) this;
        }

        public Criteria andTableZhNameNotEqualTo(String value) {
            addCriterion("table_zh_name <>", value, "tableZhName");
            return (Criteria) this;
        }

        public Criteria andTableZhNameGreaterThan(String value) {
            addCriterion("table_zh_name >", value, "tableZhName");
            return (Criteria) this;
        }

        public Criteria andTableZhNameGreaterThanOrEqualTo(String value) {
            addCriterion("table_zh_name >=", value, "tableZhName");
            return (Criteria) this;
        }

        public Criteria andTableZhNameLessThan(String value) {
            addCriterion("table_zh_name <", value, "tableZhName");
            return (Criteria) this;
        }

        public Criteria andTableZhNameLessThanOrEqualTo(String value) {
            addCriterion("table_zh_name <=", value, "tableZhName");
            return (Criteria) this;
        }

        public Criteria andTableZhNameLike(String value) {
            addCriterion("table_zh_name like", value, "tableZhName");
            return (Criteria) this;
        }

        public Criteria andTableZhNameNotLike(String value) {
            addCriterion("table_zh_name not like", value, "tableZhName");
            return (Criteria) this;
        }

        public Criteria andTableZhNameIn(List<String> values) {
            addCriterion("table_zh_name in", values, "tableZhName");
            return (Criteria) this;
        }

        public Criteria andTableZhNameNotIn(List<String> values) {
            addCriterion("table_zh_name not in", values, "tableZhName");
            return (Criteria) this;
        }

        public Criteria andTableZhNameBetween(String value1, String value2) {
            addCriterion("table_zh_name between", value1, value2, "tableZhName");
            return (Criteria) this;
        }

        public Criteria andTableZhNameNotBetween(String value1, String value2) {
            addCriterion("table_zh_name not between", value1, value2, "tableZhName");
            return (Criteria) this;
        }

        public Criteria andTableNameIsNull() {
            addCriterion("table_name is null");
            return (Criteria) this;
        }

        public Criteria andTableNameIsNotNull() {
            addCriterion("table_name is not null");
            return (Criteria) this;
        }

        public Criteria andTableNameEqualTo(String value) {
            addCriterion("table_name =", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotEqualTo(String value) {
            addCriterion("table_name <>", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameGreaterThan(String value) {
            addCriterion("table_name >", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameGreaterThanOrEqualTo(String value) {
            addCriterion("table_name >=", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLessThan(String value) {
            addCriterion("table_name <", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLessThanOrEqualTo(String value) {
            addCriterion("table_name <=", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLike(String value) {
            addCriterion("table_name like", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotLike(String value) {
            addCriterion("table_name not like", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameIn(List<String> values) {
            addCriterion("table_name in", values, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotIn(List<String> values) {
            addCriterion("table_name not in", values, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameBetween(String value1, String value2) {
            addCriterion("table_name between", value1, value2, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotBetween(String value1, String value2) {
            addCriterion("table_name not between", value1, value2, "tableName");
            return (Criteria) this;
        }

        public Criteria andTargetDbIdIsNull() {
            addCriterion("target_db_id is null");
            return (Criteria) this;
        }

        public Criteria andTargetDbIdIsNotNull() {
            addCriterion("target_db_id is not null");
            return (Criteria) this;
        }

        public Criteria andTargetDbIdEqualTo(Long value) {
            addCriterion("target_db_id =", value, "targetDbId");
            return (Criteria) this;
        }

        public Criteria andTargetDbIdNotEqualTo(Long value) {
            addCriterion("target_db_id <>", value, "targetDbId");
            return (Criteria) this;
        }

        public Criteria andTargetDbIdGreaterThan(Long value) {
            addCriterion("target_db_id >", value, "targetDbId");
            return (Criteria) this;
        }

        public Criteria andTargetDbIdGreaterThanOrEqualTo(Long value) {
            addCriterion("target_db_id >=", value, "targetDbId");
            return (Criteria) this;
        }

        public Criteria andTargetDbIdLessThan(Long value) {
            addCriterion("target_db_id <", value, "targetDbId");
            return (Criteria) this;
        }

        public Criteria andTargetDbIdLessThanOrEqualTo(Long value) {
            addCriterion("target_db_id <=", value, "targetDbId");
            return (Criteria) this;
        }

        public Criteria andTargetDbIdIn(List<Long> values) {
            addCriterion("target_db_id in", values, "targetDbId");
            return (Criteria) this;
        }

        public Criteria andTargetDbIdNotIn(List<Long> values) {
            addCriterion("target_db_id not in", values, "targetDbId");
            return (Criteria) this;
        }

        public Criteria andTargetDbIdBetween(Long value1, Long value2) {
            addCriterion("target_db_id between", value1, value2, "targetDbId");
            return (Criteria) this;
        }

        public Criteria andTargetDbIdNotBetween(Long value1, Long value2) {
            addCriterion("target_db_id not between", value1, value2, "targetDbId");
            return (Criteria) this;
        }

        public Criteria andSourceDepartIdIsNull() {
            addCriterion("source_depart_id is null");
            return (Criteria) this;
        }

        public Criteria andSourceDepartIdIsNotNull() {
            addCriterion("source_depart_id is not null");
            return (Criteria) this;
        }

        public Criteria andSourceDepartIdEqualTo(Long value) {
            addCriterion("source_depart_id =", value, "sourceDepartId");
            return (Criteria) this;
        }

        public Criteria andSourceDepartIdNotEqualTo(Long value) {
            addCriterion("source_depart_id <>", value, "sourceDepartId");
            return (Criteria) this;
        }

        public Criteria andSourceDepartIdGreaterThan(Long value) {
            addCriterion("source_depart_id >", value, "sourceDepartId");
            return (Criteria) this;
        }

        public Criteria andSourceDepartIdGreaterThanOrEqualTo(Long value) {
            addCriterion("source_depart_id >=", value, "sourceDepartId");
            return (Criteria) this;
        }

        public Criteria andSourceDepartIdLessThan(Long value) {
            addCriterion("source_depart_id <", value, "sourceDepartId");
            return (Criteria) this;
        }

        public Criteria andSourceDepartIdLessThanOrEqualTo(Long value) {
            addCriterion("source_depart_id <=", value, "sourceDepartId");
            return (Criteria) this;
        }

        public Criteria andSourceDepartIdIn(List<Long> values) {
            addCriterion("source_depart_id in", values, "sourceDepartId");
            return (Criteria) this;
        }

        public Criteria andSourceDepartIdNotIn(List<Long> values) {
            addCriterion("source_depart_id not in", values, "sourceDepartId");
            return (Criteria) this;
        }

        public Criteria andSourceDepartIdBetween(Long value1, Long value2) {
            addCriterion("source_depart_id between", value1, value2, "sourceDepartId");
            return (Criteria) this;
        }

        public Criteria andSourceDepartIdNotBetween(Long value1, Long value2) {
            addCriterion("source_depart_id not between", value1, value2, "sourceDepartId");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andIsPublicIsNull() {
            addCriterion("is_public is null");
            return (Criteria) this;
        }

        public Criteria andIsPublicIsNotNull() {
            addCriterion("is_public is not null");
            return (Criteria) this;
        }

        public Criteria andIsPublicEqualTo(Integer value) {
            addCriterion("is_public =", value, "isPublic");
            return (Criteria) this;
        }

        public Criteria andIsPublicNotEqualTo(Integer value) {
            addCriterion("is_public <>", value, "isPublic");
            return (Criteria) this;
        }

        public Criteria andIsPublicGreaterThan(Integer value) {
            addCriterion("is_public >", value, "isPublic");
            return (Criteria) this;
        }

        public Criteria andIsPublicGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_public >=", value, "isPublic");
            return (Criteria) this;
        }

        public Criteria andIsPublicLessThan(Integer value) {
            addCriterion("is_public <", value, "isPublic");
            return (Criteria) this;
        }

        public Criteria andIsPublicLessThanOrEqualTo(Integer value) {
            addCriterion("is_public <=", value, "isPublic");
            return (Criteria) this;
        }

        public Criteria andIsPublicIn(List<Integer> values) {
            addCriterion("is_public in", values, "isPublic");
            return (Criteria) this;
        }

        public Criteria andIsPublicNotIn(List<Integer> values) {
            addCriterion("is_public not in", values, "isPublic");
            return (Criteria) this;
        }

        public Criteria andIsPublicBetween(Integer value1, Integer value2) {
            addCriterion("is_public between", value1, value2, "isPublic");
            return (Criteria) this;
        }

        public Criteria andIsPublicNotBetween(Integer value1, Integer value2) {
            addCriterion("is_public not between", value1, value2, "isPublic");
            return (Criteria) this;
        }

        public Criteria andGiveUrlIsNull() {
            addCriterion("give_url is null");
            return (Criteria) this;
        }

        public Criteria andGiveUrlIsNotNull() {
            addCriterion("give_url is not null");
            return (Criteria) this;
        }

        public Criteria andGiveUrlEqualTo(String value) {
            addCriterion("give_url =", value, "giveUrl");
            return (Criteria) this;
        }

        public Criteria andGiveUrlNotEqualTo(String value) {
            addCriterion("give_url <>", value, "giveUrl");
            return (Criteria) this;
        }

        public Criteria andGiveUrlGreaterThan(String value) {
            addCriterion("give_url >", value, "giveUrl");
            return (Criteria) this;
        }

        public Criteria andGiveUrlGreaterThanOrEqualTo(String value) {
            addCriterion("give_url >=", value, "giveUrl");
            return (Criteria) this;
        }

        public Criteria andGiveUrlLessThan(String value) {
            addCriterion("give_url <", value, "giveUrl");
            return (Criteria) this;
        }

        public Criteria andGiveUrlLessThanOrEqualTo(String value) {
            addCriterion("give_url <=", value, "giveUrl");
            return (Criteria) this;
        }

        public Criteria andGiveUrlLike(String value) {
            addCriterion("give_url like", value, "giveUrl");
            return (Criteria) this;
        }

        public Criteria andGiveUrlNotLike(String value) {
            addCriterion("give_url not like", value, "giveUrl");
            return (Criteria) this;
        }

        public Criteria andGiveUrlIn(List<String> values) {
            addCriterion("give_url in", values, "giveUrl");
            return (Criteria) this;
        }

        public Criteria andGiveUrlNotIn(List<String> values) {
            addCriterion("give_url not in", values, "giveUrl");
            return (Criteria) this;
        }

        public Criteria andGiveUrlBetween(String value1, String value2) {
            addCriterion("give_url between", value1, value2, "giveUrl");
            return (Criteria) this;
        }

        public Criteria andGiveUrlNotBetween(String value1, String value2) {
            addCriterion("give_url not between", value1, value2, "giveUrl");
            return (Criteria) this;
        }

        public Criteria andGiveTypeIsNull() {
            addCriterion("give_type is null");
            return (Criteria) this;
        }

        public Criteria andGiveTypeIsNotNull() {
            addCriterion("give_type is not null");
            return (Criteria) this;
        }

        public Criteria andGiveTypeEqualTo(Integer value) {
            addCriterion("give_type =", value, "giveType");
            return (Criteria) this;
        }

        public Criteria andGiveTypeNotEqualTo(Integer value) {
            addCriterion("give_type <>", value, "giveType");
            return (Criteria) this;
        }

        public Criteria andGiveTypeGreaterThan(Integer value) {
            addCriterion("give_type >", value, "giveType");
            return (Criteria) this;
        }

        public Criteria andGiveTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("give_type >=", value, "giveType");
            return (Criteria) this;
        }

        public Criteria andGiveTypeLessThan(Integer value) {
            addCriterion("give_type <", value, "giveType");
            return (Criteria) this;
        }

        public Criteria andGiveTypeLessThanOrEqualTo(Integer value) {
            addCriterion("give_type <=", value, "giveType");
            return (Criteria) this;
        }

        public Criteria andGiveTypeIn(List<Integer> values) {
            addCriterion("give_type in", values, "giveType");
            return (Criteria) this;
        }

        public Criteria andGiveTypeNotIn(List<Integer> values) {
            addCriterion("give_type not in", values, "giveType");
            return (Criteria) this;
        }

        public Criteria andGiveTypeBetween(Integer value1, Integer value2) {
            addCriterion("give_type between", value1, value2, "giveType");
            return (Criteria) this;
        }

        public Criteria andGiveTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("give_type not between", value1, value2, "giveType");
            return (Criteria) this;
        }

        public Criteria andDataLevelIsNull() {
            addCriterion("data_level is null");
            return (Criteria) this;
        }

        public Criteria andDataLevelIsNotNull() {
            addCriterion("data_level is not null");
            return (Criteria) this;
        }

        public Criteria andDataLevelEqualTo(Integer value) {
            addCriterion("data_level =", value, "dataLevel");
            return (Criteria) this;
        }

        public Criteria andDataLevelNotEqualTo(Integer value) {
            addCriterion("data_level <>", value, "dataLevel");
            return (Criteria) this;
        }

        public Criteria andDataLevelGreaterThan(Integer value) {
            addCriterion("data_level >", value, "dataLevel");
            return (Criteria) this;
        }

        public Criteria andDataLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("data_level >=", value, "dataLevel");
            return (Criteria) this;
        }

        public Criteria andDataLevelLessThan(Integer value) {
            addCriterion("data_level <", value, "dataLevel");
            return (Criteria) this;
        }

        public Criteria andDataLevelLessThanOrEqualTo(Integer value) {
            addCriterion("data_level <=", value, "dataLevel");
            return (Criteria) this;
        }

        public Criteria andDataLevelIn(List<Integer> values) {
            addCriterion("data_level in", values, "dataLevel");
            return (Criteria) this;
        }

        public Criteria andDataLevelNotIn(List<Integer> values) {
            addCriterion("data_level not in", values, "dataLevel");
            return (Criteria) this;
        }

        public Criteria andDataLevelBetween(Integer value1, Integer value2) {
            addCriterion("data_level between", value1, value2, "dataLevel");
            return (Criteria) this;
        }

        public Criteria andDataLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("data_level not between", value1, value2, "dataLevel");
            return (Criteria) this;
        }

        public Criteria andDataDescribeIsNull() {
            addCriterion("data_describe is null");
            return (Criteria) this;
        }

        public Criteria andDataDescribeIsNotNull() {
            addCriterion("data_describe is not null");
            return (Criteria) this;
        }

        public Criteria andDataDescribeEqualTo(String value) {
            addCriterion("data_describe =", value, "dataDescribe");
            return (Criteria) this;
        }

        public Criteria andDataDescribeNotEqualTo(String value) {
            addCriterion("data_describe <>", value, "dataDescribe");
            return (Criteria) this;
        }

        public Criteria andDataDescribeGreaterThan(String value) {
            addCriterion("data_describe >", value, "dataDescribe");
            return (Criteria) this;
        }

        public Criteria andDataDescribeGreaterThanOrEqualTo(String value) {
            addCriterion("data_describe >=", value, "dataDescribe");
            return (Criteria) this;
        }

        public Criteria andDataDescribeLessThan(String value) {
            addCriterion("data_describe <", value, "dataDescribe");
            return (Criteria) this;
        }

        public Criteria andDataDescribeLessThanOrEqualTo(String value) {
            addCriterion("data_describe <=", value, "dataDescribe");
            return (Criteria) this;
        }

        public Criteria andDataDescribeLike(String value) {
            addCriterion("data_describe like", value, "dataDescribe");
            return (Criteria) this;
        }

        public Criteria andDataDescribeNotLike(String value) {
            addCriterion("data_describe not like", value, "dataDescribe");
            return (Criteria) this;
        }

        public Criteria andDataDescribeIn(List<String> values) {
            addCriterion("data_describe in", values, "dataDescribe");
            return (Criteria) this;
        }

        public Criteria andDataDescribeNotIn(List<String> values) {
            addCriterion("data_describe not in", values, "dataDescribe");
            return (Criteria) this;
        }

        public Criteria andDataDescribeBetween(String value1, String value2) {
            addCriterion("data_describe between", value1, value2, "dataDescribe");
            return (Criteria) this;
        }

        public Criteria andDataDescribeNotBetween(String value1, String value2) {
            addCriterion("data_describe not between", value1, value2, "dataDescribe");
            return (Criteria) this;
        }

        public Criteria andAttentionIsNull() {
            addCriterion("attention is null");
            return (Criteria) this;
        }

        public Criteria andAttentionIsNotNull() {
            addCriterion("attention is not null");
            return (Criteria) this;
        }

        public Criteria andAttentionEqualTo(String value) {
            addCriterion("attention =", value, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionNotEqualTo(String value) {
            addCriterion("attention <>", value, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionGreaterThan(String value) {
            addCriterion("attention >", value, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionGreaterThanOrEqualTo(String value) {
            addCriterion("attention >=", value, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionLessThan(String value) {
            addCriterion("attention <", value, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionLessThanOrEqualTo(String value) {
            addCriterion("attention <=", value, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionLike(String value) {
            addCriterion("attention like", value, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionNotLike(String value) {
            addCriterion("attention not like", value, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionIn(List<String> values) {
            addCriterion("attention in", values, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionNotIn(List<String> values) {
            addCriterion("attention not in", values, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionBetween(String value1, String value2) {
            addCriterion("attention between", value1, value2, "attention");
            return (Criteria) this;
        }

        public Criteria andAttentionNotBetween(String value1, String value2) {
            addCriterion("attention not between", value1, value2, "attention");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(LocalDateTime value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(LocalDateTime value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(LocalDateTime value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<LocalDateTime> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("create_by is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("create_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(Integer value) {
            addCriterion("create_by =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(Integer value) {
            addCriterion("create_by <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(Integer value) {
            addCriterion("create_by >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_by >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(Integer value) {
            addCriterion("create_by <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(Integer value) {
            addCriterion("create_by <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<Integer> values) {
            addCriterion("create_by in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<Integer> values) {
            addCriterion("create_by not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(Integer value1, Integer value2) {
            addCriterion("create_by between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(Integer value1, Integer value2) {
            addCriterion("create_by not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(LocalDateTime value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(LocalDateTime value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(LocalDateTime value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<LocalDateTime> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("update_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("update_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(Integer value) {
            addCriterion("update_by =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(Integer value) {
            addCriterion("update_by <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(Integer value) {
            addCriterion("update_by >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_by >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(Integer value) {
            addCriterion("update_by <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(Integer value) {
            addCriterion("update_by <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<Integer> values) {
            addCriterion("update_by in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<Integer> values) {
            addCriterion("update_by not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(Integer value1, Integer value2) {
            addCriterion("update_by between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(Integer value1, Integer value2) {
            addCriterion("update_by not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andNetIdIsNull() {
            addCriterion("net_id is null");
            return (Criteria) this;
        }

        public Criteria andNetIdIsNotNull() {
            addCriterion("net_id is not null");
            return (Criteria) this;
        }

        public Criteria andNetIdEqualTo(Integer value) {
            addCriterion("net_id =", value, "netId");
            return (Criteria) this;
        }

        public Criteria andNetIdNotEqualTo(Integer value) {
            addCriterion("net_id <>", value, "netId");
            return (Criteria) this;
        }

        public Criteria andNetIdGreaterThan(Integer value) {
            addCriterion("net_id >", value, "netId");
            return (Criteria) this;
        }

        public Criteria andNetIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("net_id >=", value, "netId");
            return (Criteria) this;
        }

        public Criteria andNetIdLessThan(Integer value) {
            addCriterion("net_id <", value, "netId");
            return (Criteria) this;
        }

        public Criteria andNetIdLessThanOrEqualTo(Integer value) {
            addCriterion("net_id <=", value, "netId");
            return (Criteria) this;
        }

        public Criteria andNetIdIn(List<Integer> values) {
            addCriterion("net_id in", values, "netId");
            return (Criteria) this;
        }

        public Criteria andNetIdNotIn(List<Integer> values) {
            addCriterion("net_id not in", values, "netId");
            return (Criteria) this;
        }

        public Criteria andNetIdBetween(Integer value1, Integer value2) {
            addCriterion("net_id between", value1, value2, "netId");
            return (Criteria) this;
        }

        public Criteria andNetIdNotBetween(Integer value1, Integer value2) {
            addCriterion("net_id not between", value1, value2, "netId");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("del_flag is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("del_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Boolean value) {
            addCriterion("del_flag =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Boolean value) {
            addCriterion("del_flag <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Boolean value) {
            addCriterion("del_flag >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("del_flag >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Boolean value) {
            addCriterion("del_flag <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("del_flag <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Boolean> values) {
            addCriterion("del_flag in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Boolean> values) {
            addCriterion("del_flag not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("del_flag between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("del_flag not between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andCreateFlagIsNull() {
            addCriterion("create_flag is null");
            return (Criteria) this;
        }

        public Criteria andCreateFlagIsNotNull() {
            addCriterion("create_flag is not null");
            return (Criteria) this;
        }

        public Criteria andCreateFlagEqualTo(Boolean value) {
            addCriterion("create_flag =", value, "createFlag");
            return (Criteria) this;
        }

        public Criteria andCreateFlagNotEqualTo(Boolean value) {
            addCriterion("create_flag <>", value, "createFlag");
            return (Criteria) this;
        }

        public Criteria andCreateFlagGreaterThan(Boolean value) {
            addCriterion("create_flag >", value, "createFlag");
            return (Criteria) this;
        }

        public Criteria andCreateFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("create_flag >=", value, "createFlag");
            return (Criteria) this;
        }

        public Criteria andCreateFlagLessThan(Boolean value) {
            addCriterion("create_flag <", value, "createFlag");
            return (Criteria) this;
        }

        public Criteria andCreateFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("create_flag <=", value, "createFlag");
            return (Criteria) this;
        }

        public Criteria andCreateFlagIn(List<Boolean> values) {
            addCriterion("create_flag in", values, "createFlag");
            return (Criteria) this;
        }

        public Criteria andCreateFlagNotIn(List<Boolean> values) {
            addCriterion("create_flag not in", values, "createFlag");
            return (Criteria) this;
        }

        public Criteria andCreateFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("create_flag between", value1, value2, "createFlag");
            return (Criteria) this;
        }

        public Criteria andCreateFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("create_flag not between", value1, value2, "createFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table meta_table
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table meta_table
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}