package com.cun.util.es.db.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MetaDatasourceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meta_datasource
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meta_datasource
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meta_datasource
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_datasource
     *
     * @mbg.generated
     */
    public MetaDatasourceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_datasource
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_datasource
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_datasource
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_datasource
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_datasource
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_datasource
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_datasource
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_datasource
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_datasource
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_datasource
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table meta_datasource
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTableIdIsNull() {
            addCriterion("table_id is null");
            return (Criteria) this;
        }

        public Criteria andTableIdIsNotNull() {
            addCriterion("table_id is not null");
            return (Criteria) this;
        }

        public Criteria andTableIdEqualTo(Long value) {
            addCriterion("table_id =", value, "tableId");
            return (Criteria) this;
        }

        public Criteria andTableIdNotEqualTo(Long value) {
            addCriterion("table_id <>", value, "tableId");
            return (Criteria) this;
        }

        public Criteria andTableIdGreaterThan(Long value) {
            addCriterion("table_id >", value, "tableId");
            return (Criteria) this;
        }

        public Criteria andTableIdGreaterThanOrEqualTo(Long value) {
            addCriterion("table_id >=", value, "tableId");
            return (Criteria) this;
        }

        public Criteria andTableIdLessThan(Long value) {
            addCriterion("table_id <", value, "tableId");
            return (Criteria) this;
        }

        public Criteria andTableIdLessThanOrEqualTo(Long value) {
            addCriterion("table_id <=", value, "tableId");
            return (Criteria) this;
        }

        public Criteria andTableIdIn(List<Long> values) {
            addCriterion("table_id in", values, "tableId");
            return (Criteria) this;
        }

        public Criteria andTableIdNotIn(List<Long> values) {
            addCriterion("table_id not in", values, "tableId");
            return (Criteria) this;
        }

        public Criteria andTableIdBetween(Long value1, Long value2) {
            addCriterion("table_id between", value1, value2, "tableId");
            return (Criteria) this;
        }

        public Criteria andTableIdNotBetween(Long value1, Long value2) {
            addCriterion("table_id not between", value1, value2, "tableId");
            return (Criteria) this;
        }

        public Criteria andFilePathIsNull() {
            addCriterion("file_path is null");
            return (Criteria) this;
        }

        public Criteria andFilePathIsNotNull() {
            addCriterion("file_path is not null");
            return (Criteria) this;
        }

        public Criteria andFilePathEqualTo(String value) {
            addCriterion("file_path =", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotEqualTo(String value) {
            addCriterion("file_path <>", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathGreaterThan(String value) {
            addCriterion("file_path >", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathGreaterThanOrEqualTo(String value) {
            addCriterion("file_path >=", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathLessThan(String value) {
            addCriterion("file_path <", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathLessThanOrEqualTo(String value) {
            addCriterion("file_path <=", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathLike(String value) {
            addCriterion("file_path like", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotLike(String value) {
            addCriterion("file_path not like", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathIn(List<String> values) {
            addCriterion("file_path in", values, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotIn(List<String> values) {
            addCriterion("file_path not in", values, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathBetween(String value1, String value2) {
            addCriterion("file_path between", value1, value2, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotBetween(String value1, String value2) {
            addCriterion("file_path not between", value1, value2, "filePath");
            return (Criteria) this;
        }

        public Criteria andDatabaseIdIsNull() {
            addCriterion("database_id is null");
            return (Criteria) this;
        }

        public Criteria andDatabaseIdIsNotNull() {
            addCriterion("database_id is not null");
            return (Criteria) this;
        }

        public Criteria andDatabaseIdEqualTo(Long value) {
            addCriterion("database_id =", value, "databaseId");
            return (Criteria) this;
        }

        public Criteria andDatabaseIdNotEqualTo(Long value) {
            addCriterion("database_id <>", value, "databaseId");
            return (Criteria) this;
        }

        public Criteria andDatabaseIdGreaterThan(Long value) {
            addCriterion("database_id >", value, "databaseId");
            return (Criteria) this;
        }

        public Criteria andDatabaseIdGreaterThanOrEqualTo(Long value) {
            addCriterion("database_id >=", value, "databaseId");
            return (Criteria) this;
        }

        public Criteria andDatabaseIdLessThan(Long value) {
            addCriterion("database_id <", value, "databaseId");
            return (Criteria) this;
        }

        public Criteria andDatabaseIdLessThanOrEqualTo(Long value) {
            addCriterion("database_id <=", value, "databaseId");
            return (Criteria) this;
        }

        public Criteria andDatabaseIdIn(List<Long> values) {
            addCriterion("database_id in", values, "databaseId");
            return (Criteria) this;
        }

        public Criteria andDatabaseIdNotIn(List<Long> values) {
            addCriterion("database_id not in", values, "databaseId");
            return (Criteria) this;
        }

        public Criteria andDatabaseIdBetween(Long value1, Long value2) {
            addCriterion("database_id between", value1, value2, "databaseId");
            return (Criteria) this;
        }

        public Criteria andDatabaseIdNotBetween(Long value1, Long value2) {
            addCriterion("database_id not between", value1, value2, "databaseId");
            return (Criteria) this;
        }

        public Criteria andSourceTableNameIsNull() {
            addCriterion("source_table_name is null");
            return (Criteria) this;
        }

        public Criteria andSourceTableNameIsNotNull() {
            addCriterion("source_table_name is not null");
            return (Criteria) this;
        }

        public Criteria andSourceTableNameEqualTo(String value) {
            addCriterion("source_table_name =", value, "sourceTableName");
            return (Criteria) this;
        }

        public Criteria andSourceTableNameNotEqualTo(String value) {
            addCriterion("source_table_name <>", value, "sourceTableName");
            return (Criteria) this;
        }

        public Criteria andSourceTableNameGreaterThan(String value) {
            addCriterion("source_table_name >", value, "sourceTableName");
            return (Criteria) this;
        }

        public Criteria andSourceTableNameGreaterThanOrEqualTo(String value) {
            addCriterion("source_table_name >=", value, "sourceTableName");
            return (Criteria) this;
        }

        public Criteria andSourceTableNameLessThan(String value) {
            addCriterion("source_table_name <", value, "sourceTableName");
            return (Criteria) this;
        }

        public Criteria andSourceTableNameLessThanOrEqualTo(String value) {
            addCriterion("source_table_name <=", value, "sourceTableName");
            return (Criteria) this;
        }

        public Criteria andSourceTableNameLike(String value) {
            addCriterion("source_table_name like", value, "sourceTableName");
            return (Criteria) this;
        }

        public Criteria andSourceTableNameNotLike(String value) {
            addCriterion("source_table_name not like", value, "sourceTableName");
            return (Criteria) this;
        }

        public Criteria andSourceTableNameIn(List<String> values) {
            addCriterion("source_table_name in", values, "sourceTableName");
            return (Criteria) this;
        }

        public Criteria andSourceTableNameNotIn(List<String> values) {
            addCriterion("source_table_name not in", values, "sourceTableName");
            return (Criteria) this;
        }

        public Criteria andSourceTableNameBetween(String value1, String value2) {
            addCriterion("source_table_name between", value1, value2, "sourceTableName");
            return (Criteria) this;
        }

        public Criteria andSourceTableNameNotBetween(String value1, String value2) {
            addCriterion("source_table_name not between", value1, value2, "sourceTableName");
            return (Criteria) this;
        }

        public Criteria andQuerySqlIsNull() {
            addCriterion("query_sql is null");
            return (Criteria) this;
        }

        public Criteria andQuerySqlIsNotNull() {
            addCriterion("query_sql is not null");
            return (Criteria) this;
        }

        public Criteria andQuerySqlEqualTo(String value) {
            addCriterion("query_sql =", value, "querySql");
            return (Criteria) this;
        }

        public Criteria andQuerySqlNotEqualTo(String value) {
            addCriterion("query_sql <>", value, "querySql");
            return (Criteria) this;
        }

        public Criteria andQuerySqlGreaterThan(String value) {
            addCriterion("query_sql >", value, "querySql");
            return (Criteria) this;
        }

        public Criteria andQuerySqlGreaterThanOrEqualTo(String value) {
            addCriterion("query_sql >=", value, "querySql");
            return (Criteria) this;
        }

        public Criteria andQuerySqlLessThan(String value) {
            addCriterion("query_sql <", value, "querySql");
            return (Criteria) this;
        }

        public Criteria andQuerySqlLessThanOrEqualTo(String value) {
            addCriterion("query_sql <=", value, "querySql");
            return (Criteria) this;
        }

        public Criteria andQuerySqlLike(String value) {
            addCriterion("query_sql like", value, "querySql");
            return (Criteria) this;
        }

        public Criteria andQuerySqlNotLike(String value) {
            addCriterion("query_sql not like", value, "querySql");
            return (Criteria) this;
        }

        public Criteria andQuerySqlIn(List<String> values) {
            addCriterion("query_sql in", values, "querySql");
            return (Criteria) this;
        }

        public Criteria andQuerySqlNotIn(List<String> values) {
            addCriterion("query_sql not in", values, "querySql");
            return (Criteria) this;
        }

        public Criteria andQuerySqlBetween(String value1, String value2) {
            addCriterion("query_sql between", value1, value2, "querySql");
            return (Criteria) this;
        }

        public Criteria andQuerySqlNotBetween(String value1, String value2) {
            addCriterion("query_sql not between", value1, value2, "querySql");
            return (Criteria) this;
        }

        public Criteria andHttpCallUrlIsNull() {
            addCriterion("http_call_url is null");
            return (Criteria) this;
        }

        public Criteria andHttpCallUrlIsNotNull() {
            addCriterion("http_call_url is not null");
            return (Criteria) this;
        }

        public Criteria andHttpCallUrlEqualTo(String value) {
            addCriterion("http_call_url =", value, "httpCallUrl");
            return (Criteria) this;
        }

        public Criteria andHttpCallUrlNotEqualTo(String value) {
            addCriterion("http_call_url <>", value, "httpCallUrl");
            return (Criteria) this;
        }

        public Criteria andHttpCallUrlGreaterThan(String value) {
            addCriterion("http_call_url >", value, "httpCallUrl");
            return (Criteria) this;
        }

        public Criteria andHttpCallUrlGreaterThanOrEqualTo(String value) {
            addCriterion("http_call_url >=", value, "httpCallUrl");
            return (Criteria) this;
        }

        public Criteria andHttpCallUrlLessThan(String value) {
            addCriterion("http_call_url <", value, "httpCallUrl");
            return (Criteria) this;
        }

        public Criteria andHttpCallUrlLessThanOrEqualTo(String value) {
            addCriterion("http_call_url <=", value, "httpCallUrl");
            return (Criteria) this;
        }

        public Criteria andHttpCallUrlLike(String value) {
            addCriterion("http_call_url like", value, "httpCallUrl");
            return (Criteria) this;
        }

        public Criteria andHttpCallUrlNotLike(String value) {
            addCriterion("http_call_url not like", value, "httpCallUrl");
            return (Criteria) this;
        }

        public Criteria andHttpCallUrlIn(List<String> values) {
            addCriterion("http_call_url in", values, "httpCallUrl");
            return (Criteria) this;
        }

        public Criteria andHttpCallUrlNotIn(List<String> values) {
            addCriterion("http_call_url not in", values, "httpCallUrl");
            return (Criteria) this;
        }

        public Criteria andHttpCallUrlBetween(String value1, String value2) {
            addCriterion("http_call_url between", value1, value2, "httpCallUrl");
            return (Criteria) this;
        }

        public Criteria andHttpCallUrlNotBetween(String value1, String value2) {
            addCriterion("http_call_url not between", value1, value2, "httpCallUrl");
            return (Criteria) this;
        }

        public Criteria andRequestMethodIsNull() {
            addCriterion("request_method is null");
            return (Criteria) this;
        }

        public Criteria andRequestMethodIsNotNull() {
            addCriterion("request_method is not null");
            return (Criteria) this;
        }

        public Criteria andRequestMethodEqualTo(String value) {
            addCriterion("request_method =", value, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodNotEqualTo(String value) {
            addCriterion("request_method <>", value, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodGreaterThan(String value) {
            addCriterion("request_method >", value, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodGreaterThanOrEqualTo(String value) {
            addCriterion("request_method >=", value, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodLessThan(String value) {
            addCriterion("request_method <", value, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodLessThanOrEqualTo(String value) {
            addCriterion("request_method <=", value, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodLike(String value) {
            addCriterion("request_method like", value, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodNotLike(String value) {
            addCriterion("request_method not like", value, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodIn(List<String> values) {
            addCriterion("request_method in", values, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodNotIn(List<String> values) {
            addCriterion("request_method not in", values, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodBetween(String value1, String value2) {
            addCriterion("request_method between", value1, value2, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodNotBetween(String value1, String value2) {
            addCriterion("request_method not between", value1, value2, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andHttpCallParamsIsNull() {
            addCriterion("http_call_params is null");
            return (Criteria) this;
        }

        public Criteria andHttpCallParamsIsNotNull() {
            addCriterion("http_call_params is not null");
            return (Criteria) this;
        }

        public Criteria andHttpCallParamsEqualTo(String value) {
            addCriterion("http_call_params =", value, "httpCallParams");
            return (Criteria) this;
        }

        public Criteria andHttpCallParamsNotEqualTo(String value) {
            addCriterion("http_call_params <>", value, "httpCallParams");
            return (Criteria) this;
        }

        public Criteria andHttpCallParamsGreaterThan(String value) {
            addCriterion("http_call_params >", value, "httpCallParams");
            return (Criteria) this;
        }

        public Criteria andHttpCallParamsGreaterThanOrEqualTo(String value) {
            addCriterion("http_call_params >=", value, "httpCallParams");
            return (Criteria) this;
        }

        public Criteria andHttpCallParamsLessThan(String value) {
            addCriterion("http_call_params <", value, "httpCallParams");
            return (Criteria) this;
        }

        public Criteria andHttpCallParamsLessThanOrEqualTo(String value) {
            addCriterion("http_call_params <=", value, "httpCallParams");
            return (Criteria) this;
        }

        public Criteria andHttpCallParamsLike(String value) {
            addCriterion("http_call_params like", value, "httpCallParams");
            return (Criteria) this;
        }

        public Criteria andHttpCallParamsNotLike(String value) {
            addCriterion("http_call_params not like", value, "httpCallParams");
            return (Criteria) this;
        }

        public Criteria andHttpCallParamsIn(List<String> values) {
            addCriterion("http_call_params in", values, "httpCallParams");
            return (Criteria) this;
        }

        public Criteria andHttpCallParamsNotIn(List<String> values) {
            addCriterion("http_call_params not in", values, "httpCallParams");
            return (Criteria) this;
        }

        public Criteria andHttpCallParamsBetween(String value1, String value2) {
            addCriterion("http_call_params between", value1, value2, "httpCallParams");
            return (Criteria) this;
        }

        public Criteria andHttpCallParamsNotBetween(String value1, String value2) {
            addCriterion("http_call_params not between", value1, value2, "httpCallParams");
            return (Criteria) this;
        }

        public Criteria andInitParamsProviderIsNull() {
            addCriterion("init_params_provider is null");
            return (Criteria) this;
        }

        public Criteria andInitParamsProviderIsNotNull() {
            addCriterion("init_params_provider is not null");
            return (Criteria) this;
        }

        public Criteria andInitParamsProviderEqualTo(String value) {
            addCriterion("init_params_provider =", value, "initParamsProvider");
            return (Criteria) this;
        }

        public Criteria andInitParamsProviderNotEqualTo(String value) {
            addCriterion("init_params_provider <>", value, "initParamsProvider");
            return (Criteria) this;
        }

        public Criteria andInitParamsProviderGreaterThan(String value) {
            addCriterion("init_params_provider >", value, "initParamsProvider");
            return (Criteria) this;
        }

        public Criteria andInitParamsProviderGreaterThanOrEqualTo(String value) {
            addCriterion("init_params_provider >=", value, "initParamsProvider");
            return (Criteria) this;
        }

        public Criteria andInitParamsProviderLessThan(String value) {
            addCriterion("init_params_provider <", value, "initParamsProvider");
            return (Criteria) this;
        }

        public Criteria andInitParamsProviderLessThanOrEqualTo(String value) {
            addCriterion("init_params_provider <=", value, "initParamsProvider");
            return (Criteria) this;
        }

        public Criteria andInitParamsProviderLike(String value) {
            addCriterion("init_params_provider like", value, "initParamsProvider");
            return (Criteria) this;
        }

        public Criteria andInitParamsProviderNotLike(String value) {
            addCriterion("init_params_provider not like", value, "initParamsProvider");
            return (Criteria) this;
        }

        public Criteria andInitParamsProviderIn(List<String> values) {
            addCriterion("init_params_provider in", values, "initParamsProvider");
            return (Criteria) this;
        }

        public Criteria andInitParamsProviderNotIn(List<String> values) {
            addCriterion("init_params_provider not in", values, "initParamsProvider");
            return (Criteria) this;
        }

        public Criteria andInitParamsProviderBetween(String value1, String value2) {
            addCriterion("init_params_provider between", value1, value2, "initParamsProvider");
            return (Criteria) this;
        }

        public Criteria andInitParamsProviderNotBetween(String value1, String value2) {
            addCriterion("init_params_provider not between", value1, value2, "initParamsProvider");
            return (Criteria) this;
        }

        public Criteria andUpdateParamsProviderIsNull() {
            addCriterion("update_params_provider is null");
            return (Criteria) this;
        }

        public Criteria andUpdateParamsProviderIsNotNull() {
            addCriterion("update_params_provider is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateParamsProviderEqualTo(String value) {
            addCriterion("update_params_provider =", value, "updateParamsProvider");
            return (Criteria) this;
        }

        public Criteria andUpdateParamsProviderNotEqualTo(String value) {
            addCriterion("update_params_provider <>", value, "updateParamsProvider");
            return (Criteria) this;
        }

        public Criteria andUpdateParamsProviderGreaterThan(String value) {
            addCriterion("update_params_provider >", value, "updateParamsProvider");
            return (Criteria) this;
        }

        public Criteria andUpdateParamsProviderGreaterThanOrEqualTo(String value) {
            addCriterion("update_params_provider >=", value, "updateParamsProvider");
            return (Criteria) this;
        }

        public Criteria andUpdateParamsProviderLessThan(String value) {
            addCriterion("update_params_provider <", value, "updateParamsProvider");
            return (Criteria) this;
        }

        public Criteria andUpdateParamsProviderLessThanOrEqualTo(String value) {
            addCriterion("update_params_provider <=", value, "updateParamsProvider");
            return (Criteria) this;
        }

        public Criteria andUpdateParamsProviderLike(String value) {
            addCriterion("update_params_provider like", value, "updateParamsProvider");
            return (Criteria) this;
        }

        public Criteria andUpdateParamsProviderNotLike(String value) {
            addCriterion("update_params_provider not like", value, "updateParamsProvider");
            return (Criteria) this;
        }

        public Criteria andUpdateParamsProviderIn(List<String> values) {
            addCriterion("update_params_provider in", values, "updateParamsProvider");
            return (Criteria) this;
        }

        public Criteria andUpdateParamsProviderNotIn(List<String> values) {
            addCriterion("update_params_provider not in", values, "updateParamsProvider");
            return (Criteria) this;
        }

        public Criteria andUpdateParamsProviderBetween(String value1, String value2) {
            addCriterion("update_params_provider between", value1, value2, "updateParamsProvider");
            return (Criteria) this;
        }

        public Criteria andUpdateParamsProviderNotBetween(String value1, String value2) {
            addCriterion("update_params_provider not between", value1, value2, "updateParamsProvider");
            return (Criteria) this;
        }

        public Criteria andReplaceParamsIsNull() {
            addCriterion("replace_params is null");
            return (Criteria) this;
        }

        public Criteria andReplaceParamsIsNotNull() {
            addCriterion("replace_params is not null");
            return (Criteria) this;
        }

        public Criteria andReplaceParamsEqualTo(Boolean value) {
            addCriterion("replace_params =", value, "replaceParams");
            return (Criteria) this;
        }

        public Criteria andReplaceParamsNotEqualTo(Boolean value) {
            addCriterion("replace_params <>", value, "replaceParams");
            return (Criteria) this;
        }

        public Criteria andReplaceParamsGreaterThan(Boolean value) {
            addCriterion("replace_params >", value, "replaceParams");
            return (Criteria) this;
        }

        public Criteria andReplaceParamsGreaterThanOrEqualTo(Boolean value) {
            addCriterion("replace_params >=", value, "replaceParams");
            return (Criteria) this;
        }

        public Criteria andReplaceParamsLessThan(Boolean value) {
            addCriterion("replace_params <", value, "replaceParams");
            return (Criteria) this;
        }

        public Criteria andReplaceParamsLessThanOrEqualTo(Boolean value) {
            addCriterion("replace_params <=", value, "replaceParams");
            return (Criteria) this;
        }

        public Criteria andReplaceParamsIn(List<Boolean> values) {
            addCriterion("replace_params in", values, "replaceParams");
            return (Criteria) this;
        }

        public Criteria andReplaceParamsNotIn(List<Boolean> values) {
            addCriterion("replace_params not in", values, "replaceParams");
            return (Criteria) this;
        }

        public Criteria andReplaceParamsBetween(Boolean value1, Boolean value2) {
            addCriterion("replace_params between", value1, value2, "replaceParams");
            return (Criteria) this;
        }

        public Criteria andReplaceParamsNotBetween(Boolean value1, Boolean value2) {
            addCriterion("replace_params not between", value1, value2, "replaceParams");
            return (Criteria) this;
        }

        public Criteria andParamsProviderIsNull() {
            addCriterion("params_provider is null");
            return (Criteria) this;
        }

        public Criteria andParamsProviderIsNotNull() {
            addCriterion("params_provider is not null");
            return (Criteria) this;
        }

        public Criteria andParamsProviderEqualTo(String value) {
            addCriterion("params_provider =", value, "paramsProvider");
            return (Criteria) this;
        }

        public Criteria andParamsProviderNotEqualTo(String value) {
            addCriterion("params_provider <>", value, "paramsProvider");
            return (Criteria) this;
        }

        public Criteria andParamsProviderGreaterThan(String value) {
            addCriterion("params_provider >", value, "paramsProvider");
            return (Criteria) this;
        }

        public Criteria andParamsProviderGreaterThanOrEqualTo(String value) {
            addCriterion("params_provider >=", value, "paramsProvider");
            return (Criteria) this;
        }

        public Criteria andParamsProviderLessThan(String value) {
            addCriterion("params_provider <", value, "paramsProvider");
            return (Criteria) this;
        }

        public Criteria andParamsProviderLessThanOrEqualTo(String value) {
            addCriterion("params_provider <=", value, "paramsProvider");
            return (Criteria) this;
        }

        public Criteria andParamsProviderLike(String value) {
            addCriterion("params_provider like", value, "paramsProvider");
            return (Criteria) this;
        }

        public Criteria andParamsProviderNotLike(String value) {
            addCriterion("params_provider not like", value, "paramsProvider");
            return (Criteria) this;
        }

        public Criteria andParamsProviderIn(List<String> values) {
            addCriterion("params_provider in", values, "paramsProvider");
            return (Criteria) this;
        }

        public Criteria andParamsProviderNotIn(List<String> values) {
            addCriterion("params_provider not in", values, "paramsProvider");
            return (Criteria) this;
        }

        public Criteria andParamsProviderBetween(String value1, String value2) {
            addCriterion("params_provider between", value1, value2, "paramsProvider");
            return (Criteria) this;
        }

        public Criteria andParamsProviderNotBetween(String value1, String value2) {
            addCriterion("params_provider not between", value1, value2, "paramsProvider");
            return (Criteria) this;
        }

        public Criteria andResultPositionIsNull() {
            addCriterion("result_position is null");
            return (Criteria) this;
        }

        public Criteria andResultPositionIsNotNull() {
            addCriterion("result_position is not null");
            return (Criteria) this;
        }

        public Criteria andResultPositionEqualTo(String value) {
            addCriterion("result_position =", value, "resultPosition");
            return (Criteria) this;
        }

        public Criteria andResultPositionNotEqualTo(String value) {
            addCriterion("result_position <>", value, "resultPosition");
            return (Criteria) this;
        }

        public Criteria andResultPositionGreaterThan(String value) {
            addCriterion("result_position >", value, "resultPosition");
            return (Criteria) this;
        }

        public Criteria andResultPositionGreaterThanOrEqualTo(String value) {
            addCriterion("result_position >=", value, "resultPosition");
            return (Criteria) this;
        }

        public Criteria andResultPositionLessThan(String value) {
            addCriterion("result_position <", value, "resultPosition");
            return (Criteria) this;
        }

        public Criteria andResultPositionLessThanOrEqualTo(String value) {
            addCriterion("result_position <=", value, "resultPosition");
            return (Criteria) this;
        }

        public Criteria andResultPositionLike(String value) {
            addCriterion("result_position like", value, "resultPosition");
            return (Criteria) this;
        }

        public Criteria andResultPositionNotLike(String value) {
            addCriterion("result_position not like", value, "resultPosition");
            return (Criteria) this;
        }

        public Criteria andResultPositionIn(List<String> values) {
            addCriterion("result_position in", values, "resultPosition");
            return (Criteria) this;
        }

        public Criteria andResultPositionNotIn(List<String> values) {
            addCriterion("result_position not in", values, "resultPosition");
            return (Criteria) this;
        }

        public Criteria andResultPositionBetween(String value1, String value2) {
            addCriterion("result_position between", value1, value2, "resultPosition");
            return (Criteria) this;
        }

        public Criteria andResultPositionNotBetween(String value1, String value2) {
            addCriterion("result_position not between", value1, value2, "resultPosition");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("del_flag is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("del_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Boolean value) {
            addCriterion("del_flag =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Boolean value) {
            addCriterion("del_flag <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Boolean value) {
            addCriterion("del_flag >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("del_flag >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Boolean value) {
            addCriterion("del_flag <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("del_flag <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Boolean> values) {
            addCriterion("del_flag in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Boolean> values) {
            addCriterion("del_flag not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("del_flag between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("del_flag not between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andParamFromTableIsNull() {
            addCriterion("param_from_table is null");
            return (Criteria) this;
        }

        public Criteria andParamFromTableIsNotNull() {
            addCriterion("param_from_table is not null");
            return (Criteria) this;
        }

        public Criteria andParamFromTableEqualTo(Boolean value) {
            addCriterion("param_from_table =", value, "paramFromTable");
            return (Criteria) this;
        }

        public Criteria andParamFromTableNotEqualTo(Boolean value) {
            addCriterion("param_from_table <>", value, "paramFromTable");
            return (Criteria) this;
        }

        public Criteria andParamFromTableGreaterThan(Boolean value) {
            addCriterion("param_from_table >", value, "paramFromTable");
            return (Criteria) this;
        }

        public Criteria andParamFromTableGreaterThanOrEqualTo(Boolean value) {
            addCriterion("param_from_table >=", value, "paramFromTable");
            return (Criteria) this;
        }

        public Criteria andParamFromTableLessThan(Boolean value) {
            addCriterion("param_from_table <", value, "paramFromTable");
            return (Criteria) this;
        }

        public Criteria andParamFromTableLessThanOrEqualTo(Boolean value) {
            addCriterion("param_from_table <=", value, "paramFromTable");
            return (Criteria) this;
        }

        public Criteria andParamFromTableIn(List<Boolean> values) {
            addCriterion("param_from_table in", values, "paramFromTable");
            return (Criteria) this;
        }

        public Criteria andParamFromTableNotIn(List<Boolean> values) {
            addCriterion("param_from_table not in", values, "paramFromTable");
            return (Criteria) this;
        }

        public Criteria andParamFromTableBetween(Boolean value1, Boolean value2) {
            addCriterion("param_from_table between", value1, value2, "paramFromTable");
            return (Criteria) this;
        }

        public Criteria andParamFromTableNotBetween(Boolean value1, Boolean value2) {
            addCriterion("param_from_table not between", value1, value2, "paramFromTable");
            return (Criteria) this;
        }

        public Criteria andFromTableNameIsNull() {
            addCriterion("from_table_name is null");
            return (Criteria) this;
        }

        public Criteria andFromTableNameIsNotNull() {
            addCriterion("from_table_name is not null");
            return (Criteria) this;
        }

        public Criteria andFromTableNameEqualTo(String value) {
            addCriterion("from_table_name =", value, "fromTableName");
            return (Criteria) this;
        }

        public Criteria andFromTableNameNotEqualTo(String value) {
            addCriterion("from_table_name <>", value, "fromTableName");
            return (Criteria) this;
        }

        public Criteria andFromTableNameGreaterThan(String value) {
            addCriterion("from_table_name >", value, "fromTableName");
            return (Criteria) this;
        }

        public Criteria andFromTableNameGreaterThanOrEqualTo(String value) {
            addCriterion("from_table_name >=", value, "fromTableName");
            return (Criteria) this;
        }

        public Criteria andFromTableNameLessThan(String value) {
            addCriterion("from_table_name <", value, "fromTableName");
            return (Criteria) this;
        }

        public Criteria andFromTableNameLessThanOrEqualTo(String value) {
            addCriterion("from_table_name <=", value, "fromTableName");
            return (Criteria) this;
        }

        public Criteria andFromTableNameLike(String value) {
            addCriterion("from_table_name like", value, "fromTableName");
            return (Criteria) this;
        }

        public Criteria andFromTableNameNotLike(String value) {
            addCriterion("from_table_name not like", value, "fromTableName");
            return (Criteria) this;
        }

        public Criteria andFromTableNameIn(List<String> values) {
            addCriterion("from_table_name in", values, "fromTableName");
            return (Criteria) this;
        }

        public Criteria andFromTableNameNotIn(List<String> values) {
            addCriterion("from_table_name not in", values, "fromTableName");
            return (Criteria) this;
        }

        public Criteria andFromTableNameBetween(String value1, String value2) {
            addCriterion("from_table_name between", value1, value2, "fromTableName");
            return (Criteria) this;
        }

        public Criteria andFromTableNameNotBetween(String value1, String value2) {
            addCriterion("from_table_name not between", value1, value2, "fromTableName");
            return (Criteria) this;
        }

        public Criteria andParamConditionIsNull() {
            addCriterion("param_condition is null");
            return (Criteria) this;
        }

        public Criteria andParamConditionIsNotNull() {
            addCriterion("param_condition is not null");
            return (Criteria) this;
        }

        public Criteria andParamConditionEqualTo(String value) {
            addCriterion("param_condition =", value, "paramCondition");
            return (Criteria) this;
        }

        public Criteria andParamConditionNotEqualTo(String value) {
            addCriterion("param_condition <>", value, "paramCondition");
            return (Criteria) this;
        }

        public Criteria andParamConditionGreaterThan(String value) {
            addCriterion("param_condition >", value, "paramCondition");
            return (Criteria) this;
        }

        public Criteria andParamConditionGreaterThanOrEqualTo(String value) {
            addCriterion("param_condition >=", value, "paramCondition");
            return (Criteria) this;
        }

        public Criteria andParamConditionLessThan(String value) {
            addCriterion("param_condition <", value, "paramCondition");
            return (Criteria) this;
        }

        public Criteria andParamConditionLessThanOrEqualTo(String value) {
            addCriterion("param_condition <=", value, "paramCondition");
            return (Criteria) this;
        }

        public Criteria andParamConditionLike(String value) {
            addCriterion("param_condition like", value, "paramCondition");
            return (Criteria) this;
        }

        public Criteria andParamConditionNotLike(String value) {
            addCriterion("param_condition not like", value, "paramCondition");
            return (Criteria) this;
        }

        public Criteria andParamConditionIn(List<String> values) {
            addCriterion("param_condition in", values, "paramCondition");
            return (Criteria) this;
        }

        public Criteria andParamConditionNotIn(List<String> values) {
            addCriterion("param_condition not in", values, "paramCondition");
            return (Criteria) this;
        }

        public Criteria andParamConditionBetween(String value1, String value2) {
            addCriterion("param_condition between", value1, value2, "paramCondition");
            return (Criteria) this;
        }

        public Criteria andParamConditionNotBetween(String value1, String value2) {
            addCriterion("param_condition not between", value1, value2, "paramCondition");
            return (Criteria) this;
        }

        public Criteria andParamTypeIsNull() {
            addCriterion("param_type is null");
            return (Criteria) this;
        }

        public Criteria andParamTypeIsNotNull() {
            addCriterion("param_type is not null");
            return (Criteria) this;
        }

        public Criteria andParamTypeEqualTo(String value) {
            addCriterion("param_type =", value, "paramType");
            return (Criteria) this;
        }

        public Criteria andParamTypeNotEqualTo(String value) {
            addCriterion("param_type <>", value, "paramType");
            return (Criteria) this;
        }

        public Criteria andParamTypeGreaterThan(String value) {
            addCriterion("param_type >", value, "paramType");
            return (Criteria) this;
        }

        public Criteria andParamTypeGreaterThanOrEqualTo(String value) {
            addCriterion("param_type >=", value, "paramType");
            return (Criteria) this;
        }

        public Criteria andParamTypeLessThan(String value) {
            addCriterion("param_type <", value, "paramType");
            return (Criteria) this;
        }

        public Criteria andParamTypeLessThanOrEqualTo(String value) {
            addCriterion("param_type <=", value, "paramType");
            return (Criteria) this;
        }

        public Criteria andParamTypeLike(String value) {
            addCriterion("param_type like", value, "paramType");
            return (Criteria) this;
        }

        public Criteria andParamTypeNotLike(String value) {
            addCriterion("param_type not like", value, "paramType");
            return (Criteria) this;
        }

        public Criteria andParamTypeIn(List<String> values) {
            addCriterion("param_type in", values, "paramType");
            return (Criteria) this;
        }

        public Criteria andParamTypeNotIn(List<String> values) {
            addCriterion("param_type not in", values, "paramType");
            return (Criteria) this;
        }

        public Criteria andParamTypeBetween(String value1, String value2) {
            addCriterion("param_type between", value1, value2, "paramType");
            return (Criteria) this;
        }

        public Criteria andParamTypeNotBetween(String value1, String value2) {
            addCriterion("param_type not between", value1, value2, "paramType");
            return (Criteria) this;
        }

        public Criteria andRequestResultTypeIsNull() {
            addCriterion("request_result_type is null");
            return (Criteria) this;
        }

        public Criteria andRequestResultTypeIsNotNull() {
            addCriterion("request_result_type is not null");
            return (Criteria) this;
        }

        public Criteria andRequestResultTypeEqualTo(String value) {
            addCriterion("request_result_type =", value, "requestResultType");
            return (Criteria) this;
        }

        public Criteria andRequestResultTypeNotEqualTo(String value) {
            addCriterion("request_result_type <>", value, "requestResultType");
            return (Criteria) this;
        }

        public Criteria andRequestResultTypeGreaterThan(String value) {
            addCriterion("request_result_type >", value, "requestResultType");
            return (Criteria) this;
        }

        public Criteria andRequestResultTypeGreaterThanOrEqualTo(String value) {
            addCriterion("request_result_type >=", value, "requestResultType");
            return (Criteria) this;
        }

        public Criteria andRequestResultTypeLessThan(String value) {
            addCriterion("request_result_type <", value, "requestResultType");
            return (Criteria) this;
        }

        public Criteria andRequestResultTypeLessThanOrEqualTo(String value) {
            addCriterion("request_result_type <=", value, "requestResultType");
            return (Criteria) this;
        }

        public Criteria andRequestResultTypeLike(String value) {
            addCriterion("request_result_type like", value, "requestResultType");
            return (Criteria) this;
        }

        public Criteria andRequestResultTypeNotLike(String value) {
            addCriterion("request_result_type not like", value, "requestResultType");
            return (Criteria) this;
        }

        public Criteria andRequestResultTypeIn(List<String> values) {
            addCriterion("request_result_type in", values, "requestResultType");
            return (Criteria) this;
        }

        public Criteria andRequestResultTypeNotIn(List<String> values) {
            addCriterion("request_result_type not in", values, "requestResultType");
            return (Criteria) this;
        }

        public Criteria andRequestResultTypeBetween(String value1, String value2) {
            addCriterion("request_result_type between", value1, value2, "requestResultType");
            return (Criteria) this;
        }

        public Criteria andRequestResultTypeNotBetween(String value1, String value2) {
            addCriterion("request_result_type not between", value1, value2, "requestResultType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeIsNull() {
            addCriterion("source_type is null");
            return (Criteria) this;
        }

        public Criteria andSourceTypeIsNotNull() {
            addCriterion("source_type is not null");
            return (Criteria) this;
        }

        public Criteria andSourceTypeEqualTo(Integer value) {
            addCriterion("source_type =", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeNotEqualTo(Integer value) {
            addCriterion("source_type <>", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeGreaterThan(Integer value) {
            addCriterion("source_type >", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("source_type >=", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeLessThan(Integer value) {
            addCriterion("source_type <", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeLessThanOrEqualTo(Integer value) {
            addCriterion("source_type <=", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeIn(List<Integer> values) {
            addCriterion("source_type in", values, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeNotIn(List<Integer> values) {
            addCriterion("source_type not in", values, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeBetween(Integer value1, Integer value2) {
            addCriterion("source_type between", value1, value2, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("source_type not between", value1, value2, "sourceType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table meta_datasource
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table meta_datasource
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}