package com.cun.util.es.db.pojo;

import java.time.LocalDateTime;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table meta_table
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class MetaTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_table.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   分类编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_table.catalog_id
     *
     * @mbg.generated
     */
    private Long catalogId;

    /**
     * Database Column Remarks:
     *   主题编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_table.theme_id
     *
     * @mbg.generated
     */
    private Long themeId;

    /**
     * Database Column Remarks:
     *   名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_table.table_zh_name
     *
     * @mbg.generated
     */
    private String tableZhName;

    /**
     * Database Column Remarks:
     *   表名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_table.table_name
     *
     * @mbg.generated
     */
    private String tableName;

    /**
     * Database Column Remarks:
     *   数据落地库
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_table.target_db_id
     *
     * @mbg.generated
     */
    private Long targetDbId;

    /**
     * Database Column Remarks:
     *   数据来源部⻔编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_table.source_depart_id
     *
     * @mbg.generated
     */
    private Long sourceDepartId;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_table.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   是否公开数据
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_table.is_public
     *
     * @mbg.generated
     */
    private Integer isPublic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_table.give_url
     *
     * @mbg.generated
     */
    private String giveUrl;

    /**
     * Database Column Remarks:
     *   数据提供方式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_table.give_type
     *
     * @mbg.generated
     */
    private Integer giveType;

    /**
     * Database Column Remarks:
     *   数据所属层级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_table.data_level
     *
     * @mbg.generated
     */
    private Integer dataLevel;

    /**
     * Database Column Remarks:
     *   数据简介
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_table.data_describe
     *
     * @mbg.generated
     */
    private String dataDescribe;

    /**
     * Database Column Remarks:
     *   接⼊须知
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_table.attention
     *
     * @mbg.generated
     */
    private String attention;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_table.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     * Database Column Remarks:
     *   创建⼈
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_table.create_by
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     * Database Column Remarks:
     *   修改⽇期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_table.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     * Database Column Remarks:
     *   修改⼈
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_table.update_by
     *
     * @mbg.generated
     */
    private Integer updateBy;

    /**
     * Database Column Remarks:
     *   所属⽹格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_table.net_id
     *
     * @mbg.generated
     */
    private Integer netId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_table.del_flag
     *
     * @mbg.generated
     */
    private Boolean delFlag;

    /**
     * Database Column Remarks:
     *   是否已经创建表
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_table.create_flag
     *
     * @mbg.generated
     */
    private Boolean createFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_table.id
     *
     * @return the value of meta_table.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_table.id
     *
     * @param id the value for meta_table.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_table.catalog_id
     *
     * @return the value of meta_table.catalog_id
     *
     * @mbg.generated
     */
    public Long getCatalogId() {
        return catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_table.catalog_id
     *
     * @param catalogId the value for meta_table.catalog_id
     *
     * @mbg.generated
     */
    public void setCatalogId(Long catalogId) {
        this.catalogId = catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_table.theme_id
     *
     * @return the value of meta_table.theme_id
     *
     * @mbg.generated
     */
    public Long getThemeId() {
        return themeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_table.theme_id
     *
     * @param themeId the value for meta_table.theme_id
     *
     * @mbg.generated
     */
    public void setThemeId(Long themeId) {
        this.themeId = themeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_table.table_zh_name
     *
     * @return the value of meta_table.table_zh_name
     *
     * @mbg.generated
     */
    public String getTableZhName() {
        return tableZhName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_table.table_zh_name
     *
     * @param tableZhName the value for meta_table.table_zh_name
     *
     * @mbg.generated
     */
    public void setTableZhName(String tableZhName) {
        this.tableZhName = tableZhName == null ? null : tableZhName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_table.table_name
     *
     * @return the value of meta_table.table_name
     *
     * @mbg.generated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_table.table_name
     *
     * @param tableName the value for meta_table.table_name
     *
     * @mbg.generated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_table.target_db_id
     *
     * @return the value of meta_table.target_db_id
     *
     * @mbg.generated
     */
    public Long getTargetDbId() {
        return targetDbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_table.target_db_id
     *
     * @param targetDbId the value for meta_table.target_db_id
     *
     * @mbg.generated
     */
    public void setTargetDbId(Long targetDbId) {
        this.targetDbId = targetDbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_table.source_depart_id
     *
     * @return the value of meta_table.source_depart_id
     *
     * @mbg.generated
     */
    public Long getSourceDepartId() {
        return sourceDepartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_table.source_depart_id
     *
     * @param sourceDepartId the value for meta_table.source_depart_id
     *
     * @mbg.generated
     */
    public void setSourceDepartId(Long sourceDepartId) {
        this.sourceDepartId = sourceDepartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_table.status
     *
     * @return the value of meta_table.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_table.status
     *
     * @param status the value for meta_table.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_table.is_public
     *
     * @return the value of meta_table.is_public
     *
     * @mbg.generated
     */
    public Integer getIsPublic() {
        return isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_table.is_public
     *
     * @param isPublic the value for meta_table.is_public
     *
     * @mbg.generated
     */
    public void setIsPublic(Integer isPublic) {
        this.isPublic = isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_table.give_url
     *
     * @return the value of meta_table.give_url
     *
     * @mbg.generated
     */
    public String getGiveUrl() {
        return giveUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_table.give_url
     *
     * @param giveUrl the value for meta_table.give_url
     *
     * @mbg.generated
     */
    public void setGiveUrl(String giveUrl) {
        this.giveUrl = giveUrl == null ? null : giveUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_table.give_type
     *
     * @return the value of meta_table.give_type
     *
     * @mbg.generated
     */
    public Integer getGiveType() {
        return giveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_table.give_type
     *
     * @param giveType the value for meta_table.give_type
     *
     * @mbg.generated
     */
    public void setGiveType(Integer giveType) {
        this.giveType = giveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_table.data_level
     *
     * @return the value of meta_table.data_level
     *
     * @mbg.generated
     */
    public Integer getDataLevel() {
        return dataLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_table.data_level
     *
     * @param dataLevel the value for meta_table.data_level
     *
     * @mbg.generated
     */
    public void setDataLevel(Integer dataLevel) {
        this.dataLevel = dataLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_table.data_describe
     *
     * @return the value of meta_table.data_describe
     *
     * @mbg.generated
     */
    public String getDataDescribe() {
        return dataDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_table.data_describe
     *
     * @param dataDescribe the value for meta_table.data_describe
     *
     * @mbg.generated
     */
    public void setDataDescribe(String dataDescribe) {
        this.dataDescribe = dataDescribe == null ? null : dataDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_table.attention
     *
     * @return the value of meta_table.attention
     *
     * @mbg.generated
     */
    public String getAttention() {
        return attention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_table.attention
     *
     * @param attention the value for meta_table.attention
     *
     * @mbg.generated
     */
    public void setAttention(String attention) {
        this.attention = attention == null ? null : attention.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_table.create_time
     *
     * @return the value of meta_table.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_table.create_time
     *
     * @param createTime the value for meta_table.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_table.create_by
     *
     * @return the value of meta_table.create_by
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_table.create_by
     *
     * @param createBy the value for meta_table.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_table.update_time
     *
     * @return the value of meta_table.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_table.update_time
     *
     * @param updateTime the value for meta_table.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_table.update_by
     *
     * @return the value of meta_table.update_by
     *
     * @mbg.generated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_table.update_by
     *
     * @param updateBy the value for meta_table.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_table.net_id
     *
     * @return the value of meta_table.net_id
     *
     * @mbg.generated
     */
    public Integer getNetId() {
        return netId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_table.net_id
     *
     * @param netId the value for meta_table.net_id
     *
     * @mbg.generated
     */
    public void setNetId(Integer netId) {
        this.netId = netId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_table.del_flag
     *
     * @return the value of meta_table.del_flag
     *
     * @mbg.generated
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_table.del_flag
     *
     * @param delFlag the value for meta_table.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_table.create_flag
     *
     * @return the value of meta_table.create_flag
     *
     * @mbg.generated
     */
    public Boolean getCreateFlag() {
        return createFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_table.create_flag
     *
     * @param createFlag the value for meta_table.create_flag
     *
     * @mbg.generated
     */
    public void setCreateFlag(Boolean createFlag) {
        this.createFlag = createFlag;
    }
}