package com.cun.util.es.db.pojo;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table meta_datasource
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class MetaDatasource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_datasource.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   关联数据表id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_datasource.table_id
     *
     * @mbg.generated
     */
    private Long tableId;

    /**
     * Database Column Remarks:
     *   ⽂件路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_datasource.file_path
     *
     * @mbg.generated
     */
    private String filePath;

    /**
     * Database Column Remarks:
     *   数据连接id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_datasource.database_id
     *
     * @mbg.generated
     */
    private Long databaseId;

    /**
     * Database Column Remarks:
     *   来源表名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_datasource.source_table_name
     *
     * @mbg.generated
     */
    private String sourceTableName;

    /**
     * Database Column Remarks:
     *   存储过程
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_datasource.query_sql
     *
     * @mbg.generated
     */
    private String querySql;

    /**
     * Database Column Remarks:
     *   接⼝地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_datasource.http_call_url
     *
     * @mbg.generated
     */
    private String httpCallUrl;

    /**
     * Database Column Remarks:
     *   接⼝类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_datasource.request_method
     *
     * @mbg.generated
     */
    private String requestMethod;

    /**
     * Database Column Remarks:
     *   接⼝参数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_datasource.http_call_params
     *
     * @mbg.generated
     */
    private String httpCallParams;

    /**
     * Database Column Remarks:
     *   ⽣成⾸次拉取数据的参数⽣成类
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_datasource.init_params_provider
     *
     * @mbg.generated
     */
    private String initParamsProvider;

    /**
     * Database Column Remarks:
     *   更新数据的参数⽣成类
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_datasource.update_params_provider
     *
     * @mbg.generated
     */
    private String updateParamsProvider;

    /**
     * Database Column Remarks:
     *   是否需要替换参数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_datasource.replace_params
     *
     * @mbg.generated
     */
    private Boolean replaceParams;

    /**
     * Database Column Remarks:
     *   ⼊参处理器
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_datasource.params_provider
     *
     * @mbg.generated
     */
    private String paramsProvider;

    /**
     * Database Column Remarks:
     *   返回值位置
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_datasource.result_position
     *
     * @mbg.generated
     */
    private String resultPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_datasource.del_flag
     *
     * @mbg.generated
     */
    private Boolean delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_datasource.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_datasource.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   参数是否来源于数据表
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_datasource.param_from_table
     *
     * @mbg.generated
     */
    private Boolean paramFromTable;

    /**
     * Database Column Remarks:
     *   参数来源表名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_datasource.from_table_name
     *
     * @mbg.generated
     */
    private String fromTableName;

    /**
     * Database Column Remarks:
     *   参数来源取数条件
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_datasource.param_condition
     *
     * @mbg.generated
     */
    private String paramCondition;

    /**
     * Database Column Remarks:
     *   参数类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_datasource.param_type
     *
     * @mbg.generated
     */
    private String paramType;

    /**
     * Database Column Remarks:
     *   接口请求返回结果类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_datasource.request_result_type
     *
     * @mbg.generated
     */
    private String requestResultType;

    /**
     * Database Column Remarks:
     *   数据接入类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meta_datasource.source_type
     *
     * @mbg.generated
     */
    private Integer sourceType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_datasource.id
     *
     * @return the value of meta_datasource.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_datasource.id
     *
     * @param id the value for meta_datasource.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_datasource.table_id
     *
     * @return the value of meta_datasource.table_id
     *
     * @mbg.generated
     */
    public Long getTableId() {
        return tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_datasource.table_id
     *
     * @param tableId the value for meta_datasource.table_id
     *
     * @mbg.generated
     */
    public void setTableId(Long tableId) {
        this.tableId = tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_datasource.file_path
     *
     * @return the value of meta_datasource.file_path
     *
     * @mbg.generated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_datasource.file_path
     *
     * @param filePath the value for meta_datasource.file_path
     *
     * @mbg.generated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_datasource.database_id
     *
     * @return the value of meta_datasource.database_id
     *
     * @mbg.generated
     */
    public Long getDatabaseId() {
        return databaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_datasource.database_id
     *
     * @param databaseId the value for meta_datasource.database_id
     *
     * @mbg.generated
     */
    public void setDatabaseId(Long databaseId) {
        this.databaseId = databaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_datasource.source_table_name
     *
     * @return the value of meta_datasource.source_table_name
     *
     * @mbg.generated
     */
    public String getSourceTableName() {
        return sourceTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_datasource.source_table_name
     *
     * @param sourceTableName the value for meta_datasource.source_table_name
     *
     * @mbg.generated
     */
    public void setSourceTableName(String sourceTableName) {
        this.sourceTableName = sourceTableName == null ? null : sourceTableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_datasource.query_sql
     *
     * @return the value of meta_datasource.query_sql
     *
     * @mbg.generated
     */
    public String getQuerySql() {
        return querySql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_datasource.query_sql
     *
     * @param querySql the value for meta_datasource.query_sql
     *
     * @mbg.generated
     */
    public void setQuerySql(String querySql) {
        this.querySql = querySql == null ? null : querySql.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_datasource.http_call_url
     *
     * @return the value of meta_datasource.http_call_url
     *
     * @mbg.generated
     */
    public String getHttpCallUrl() {
        return httpCallUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_datasource.http_call_url
     *
     * @param httpCallUrl the value for meta_datasource.http_call_url
     *
     * @mbg.generated
     */
    public void setHttpCallUrl(String httpCallUrl) {
        this.httpCallUrl = httpCallUrl == null ? null : httpCallUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_datasource.request_method
     *
     * @return the value of meta_datasource.request_method
     *
     * @mbg.generated
     */
    public String getRequestMethod() {
        return requestMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_datasource.request_method
     *
     * @param requestMethod the value for meta_datasource.request_method
     *
     * @mbg.generated
     */
    public void setRequestMethod(String requestMethod) {
        this.requestMethod = requestMethod == null ? null : requestMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_datasource.http_call_params
     *
     * @return the value of meta_datasource.http_call_params
     *
     * @mbg.generated
     */
    public String getHttpCallParams() {
        return httpCallParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_datasource.http_call_params
     *
     * @param httpCallParams the value for meta_datasource.http_call_params
     *
     * @mbg.generated
     */
    public void setHttpCallParams(String httpCallParams) {
        this.httpCallParams = httpCallParams == null ? null : httpCallParams.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_datasource.init_params_provider
     *
     * @return the value of meta_datasource.init_params_provider
     *
     * @mbg.generated
     */
    public String getInitParamsProvider() {
        return initParamsProvider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_datasource.init_params_provider
     *
     * @param initParamsProvider the value for meta_datasource.init_params_provider
     *
     * @mbg.generated
     */
    public void setInitParamsProvider(String initParamsProvider) {
        this.initParamsProvider = initParamsProvider == null ? null : initParamsProvider.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_datasource.update_params_provider
     *
     * @return the value of meta_datasource.update_params_provider
     *
     * @mbg.generated
     */
    public String getUpdateParamsProvider() {
        return updateParamsProvider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_datasource.update_params_provider
     *
     * @param updateParamsProvider the value for meta_datasource.update_params_provider
     *
     * @mbg.generated
     */
    public void setUpdateParamsProvider(String updateParamsProvider) {
        this.updateParamsProvider = updateParamsProvider == null ? null : updateParamsProvider.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_datasource.replace_params
     *
     * @return the value of meta_datasource.replace_params
     *
     * @mbg.generated
     */
    public Boolean getReplaceParams() {
        return replaceParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_datasource.replace_params
     *
     * @param replaceParams the value for meta_datasource.replace_params
     *
     * @mbg.generated
     */
    public void setReplaceParams(Boolean replaceParams) {
        this.replaceParams = replaceParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_datasource.params_provider
     *
     * @return the value of meta_datasource.params_provider
     *
     * @mbg.generated
     */
    public String getParamsProvider() {
        return paramsProvider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_datasource.params_provider
     *
     * @param paramsProvider the value for meta_datasource.params_provider
     *
     * @mbg.generated
     */
    public void setParamsProvider(String paramsProvider) {
        this.paramsProvider = paramsProvider == null ? null : paramsProvider.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_datasource.result_position
     *
     * @return the value of meta_datasource.result_position
     *
     * @mbg.generated
     */
    public String getResultPosition() {
        return resultPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_datasource.result_position
     *
     * @param resultPosition the value for meta_datasource.result_position
     *
     * @mbg.generated
     */
    public void setResultPosition(String resultPosition) {
        this.resultPosition = resultPosition == null ? null : resultPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_datasource.del_flag
     *
     * @return the value of meta_datasource.del_flag
     *
     * @mbg.generated
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_datasource.del_flag
     *
     * @param delFlag the value for meta_datasource.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_datasource.create_time
     *
     * @return the value of meta_datasource.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_datasource.create_time
     *
     * @param createTime the value for meta_datasource.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_datasource.update_time
     *
     * @return the value of meta_datasource.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_datasource.update_time
     *
     * @param updateTime the value for meta_datasource.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_datasource.param_from_table
     *
     * @return the value of meta_datasource.param_from_table
     *
     * @mbg.generated
     */
    public Boolean getParamFromTable() {
        return paramFromTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_datasource.param_from_table
     *
     * @param paramFromTable the value for meta_datasource.param_from_table
     *
     * @mbg.generated
     */
    public void setParamFromTable(Boolean paramFromTable) {
        this.paramFromTable = paramFromTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_datasource.from_table_name
     *
     * @return the value of meta_datasource.from_table_name
     *
     * @mbg.generated
     */
    public String getFromTableName() {
        return fromTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_datasource.from_table_name
     *
     * @param fromTableName the value for meta_datasource.from_table_name
     *
     * @mbg.generated
     */
    public void setFromTableName(String fromTableName) {
        this.fromTableName = fromTableName == null ? null : fromTableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_datasource.param_condition
     *
     * @return the value of meta_datasource.param_condition
     *
     * @mbg.generated
     */
    public String getParamCondition() {
        return paramCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_datasource.param_condition
     *
     * @param paramCondition the value for meta_datasource.param_condition
     *
     * @mbg.generated
     */
    public void setParamCondition(String paramCondition) {
        this.paramCondition = paramCondition == null ? null : paramCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_datasource.param_type
     *
     * @return the value of meta_datasource.param_type
     *
     * @mbg.generated
     */
    public String getParamType() {
        return paramType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_datasource.param_type
     *
     * @param paramType the value for meta_datasource.param_type
     *
     * @mbg.generated
     */
    public void setParamType(String paramType) {
        this.paramType = paramType == null ? null : paramType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_datasource.request_result_type
     *
     * @return the value of meta_datasource.request_result_type
     *
     * @mbg.generated
     */
    public String getRequestResultType() {
        return requestResultType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_datasource.request_result_type
     *
     * @param requestResultType the value for meta_datasource.request_result_type
     *
     * @mbg.generated
     */
    public void setRequestResultType(String requestResultType) {
        this.requestResultType = requestResultType == null ? null : requestResultType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meta_datasource.source_type
     *
     * @return the value of meta_datasource.source_type
     *
     * @mbg.generated
     */
    public Integer getSourceType() {
        return sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meta_datasource.source_type
     *
     * @param sourceType the value for meta_datasource.source_type
     *
     * @mbg.generated
     */
    public void setSourceType(Integer sourceType) {
        this.sourceType = sourceType;
    }
}